// SPDX-FileCopyrightText: 2026 The igs-iec104 contributors
//
// SPDX-License-Identifier: Apache-2.0

//! Property tests (task C6): strategies that generate valid ASDUs and APDUs,
//! round trips through the encoders and decoders, the profile rules, and
//! decoders that never panic on arbitrary octets. Each property runs 10 000
//! cases.
//!
//! Values of an element are generated by decoding random octets of its size:
//! every decoder of `elements` accepts the whole range of its octets, except
//! the values that the standard forbids, which are rejected by the decoder
//! and skipped here.

use std::fmt::Debug;

use proptest::collection::vec;
use proptest::prelude::*;
use proptest::sample::select;
use proptest::strategy::ValueTree;
use proptest::test_runner::TestRunner;
use std::collections::HashSet;

use crate::apci::{
    Apdu, FrameDecoder, SequenceNumber, UnnumberedFunction, MAX_FRAME_OCTETS, MAX_SEQUENCE_NUMBER,
    START,
};
use crate::asdu::{validate_profile, Asdu, Body, Direction, InformationObject, Objects, Wire};
use crate::generated::profile::TypeId;
use crate::header::{AsduHeader, CauseOfTransmission, CommonAddress, InformationObjectAddress};

/// Largest information object address: 24 bits.
const MAX_ADDRESS: u32 = 0x00FF_FFFF;

/// Most information objects in one ASDU of a fixed-size type. Eight objects of
/// the widest profile type stay well inside the 249 octets of an ASDU.
const MAX_FIXED_OBJECTS: usize = 8;

/// The six U functions.
const FUNCTIONS: [UnnumberedFunction; 6] = [
    UnnumberedFunction::StartDtAct,
    UnnumberedFunction::StartDtCon,
    UnnumberedFunction::StopDtAct,
    UnnumberedFunction::StopDtCon,
    UnnumberedFunction::TestFrAct,
    UnnumberedFunction::TestFrCon,
];

/// A value of `T`, decoded from random octets. Values the decoder rejects are
/// skipped.
pub(crate) fn wire<T: Wire + Debug + 'static>() -> BoxedStrategy<T> {
    vec(any::<u8>(), 0..=300)
        .prop_filter_map("value the standard forbids", |bytes| {
            T::decode_prefix(&bytes).ok().map(|(value, _)| value)
        })
        .boxed()
}

fn address() -> BoxedStrategy<InformationObjectAddress> {
    (0..=MAX_ADDRESS)
        .prop_map(|value| InformationObjectAddress::new(value).expect("24 bits"))
        .boxed()
}

/// Information objects of `T`: individual addresses, and a sequence when
/// `sequence` is true. Fixed-size values come in groups of up to eight; a
/// variable-size value (the file segment) comes alone.
pub(crate) fn objects<T: Wire + Debug + Clone + 'static>(
    sequence: bool,
) -> BoxedStrategy<Objects<T>> {
    let most = if T::SIZE.is_some() {
        MAX_FIXED_OBJECTS
    } else {
        1
    };
    let individual = vec((address(), wire::<T>()), 0..=most).prop_map(|pairs| {
        Objects::Individual(
            pairs
                .into_iter()
                .map(|(address, value)| InformationObject { address, value })
                .collect(),
        )
    });
    if !sequence {
        return individual.boxed();
    }
    let sequenced = (address(), vec(wire::<T>(), 1..=most))
        .prop_map(|(address, values)| Objects::Sequence { address, values });
    prop_oneof![individual, sequenced].boxed()
}

/// Valid ASDUs of every in-profile type, that fit in one ASDU.
pub(crate) fn asdu() -> BoxedStrategy<Asdu> {
    let types: Vec<TypeId> = TypeId::ALL
        .iter()
        .copied()
        .filter(|type_id| type_id.in_profile())
        .collect();
    (
        select(types),
        any::<bool>(),
        any::<bool>(),
        any::<u8>(),
        any::<u16>(),
    )
        .prop_flat_map(|(type_id, negative, test, originator, address)| {
            let sequence = type_id.sq_allowed_mask() & 0b10 != 0;
            (
                select(type_id.cot_allowed().to_vec()),
                Body::arbitrary(type_id, sequence),
            )
                .prop_map(move |(cause, body)| {
                    let mut cot = CauseOfTransmission::new(cause).expect("cause is 0..=63");
                    cot.negative = negative;
                    cot.test = test;
                    cot.originator = originator;
                    Asdu {
                        cot,
                        common_address: CommonAddress::new(address),
                        body,
                    }
                })
        })
        .prop_filter("the ASDU fits in 249 octets", |asdu| asdu.to_vec().is_ok())
        .boxed()
}

fn sequence_number() -> BoxedStrategy<SequenceNumber> {
    (0..=MAX_SEQUENCE_NUMBER)
        .prop_map(|value| SequenceNumber::new(value).expect("15 bits"))
        .boxed()
}

/// Valid APDUs of the three formats.
pub(crate) fn apdu() -> BoxedStrategy<Apdu> {
    prop_oneof![
        (sequence_number(), sequence_number(), asdu()).prop_map(|(send, receive, asdu)| {
            Apdu::Information {
                send,
                receive,
                asdu,
            }
        }),
        sequence_number().prop_map(|receive| Apdu::Supervisory { receive }),
        select(FUNCTIONS.to_vec()).prop_map(Apdu::Unnumbered),
    ]
    .boxed()
}

/// A valid APDU with a few octets changed and the end cut off: decoders must
/// reject it or accept it, never panic.
fn mutated_apdu() -> BoxedStrategy<Vec<u8>> {
    (
        apdu(),
        vec((any::<usize>(), any::<u8>()), 0..=4),
        any::<usize>(),
    )
        .prop_map(|(apdu, edits, cut)| {
            let mut bytes = apdu.to_vec().expect("generated APDUs encode");
            let length = bytes.len();
            for (index, value) in edits {
                if let Some(slot) = bytes.get_mut(index % length) {
                    *slot = value;
                }
            }
            bytes.truncate(cut % (length + 1));
            bytes
        })
        .boxed()
}

/// Arbitrary octets, half of them starting with the start octet so that the
/// framing and the control field are reached.
fn octets() -> BoxedStrategy<Vec<u8>> {
    prop_oneof![
        vec(any::<u8>(), 0..=300),
        vec(any::<u8>(), 0..=300).prop_map(|mut bytes| {
            bytes.insert(0, START);
            bytes
        }),
    ]
    .boxed()
}

/// Feeds the chunks to one decoder and collects the frames it returns.
fn frames_of(chunks: &[&[u8]]) -> Result<Vec<Vec<u8>>, crate::error::DecodeError> {
    let mut decoder = FrameDecoder::new();
    let mut frames = Vec::new();
    for chunk in chunks {
        let mut input: &[u8] = chunk;
        while let Some(frame) = decoder.next_frame(&mut input)? {
            frames.push(frame);
        }
    }
    Ok(frames)
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(10_000))]

    /// decode(encode(x)) == x for every ASDU.
    #[test]
    fn asdu_round_trips(asdu in asdu()) {
        let bytes = asdu.to_vec().expect("filtered to fit");
        prop_assert_eq!(Asdu::decode(&bytes), Ok(asdu));
    }

    /// decode(encode(x)) == x for every APDU of the three formats.
    #[test]
    fn apdu_round_trips(apdu in apdu()) {
        let frame = apdu.to_vec().expect("generated APDUs encode");
        prop_assert_eq!(Apdu::decode(&frame), Ok(apdu));
    }

    /// The generated ASDUs follow the profile: their cause, sequence form and
    /// type are allowed in the direction the type is sent.
    #[test]
    fn generated_asdus_follow_the_profile(asdu in asdu()) {
        let monitor = validate_profile(&asdu, Direction::Monitor);
        let control = validate_profile(&asdu, Direction::Control);
        prop_assert!(
            monitor.is_ok() || control.is_ok(),
            "{:?} is rejected in both directions: {:?} / {:?}",
            asdu.type_id(),
            monitor,
            control
        );
    }

    /// Octets that are not a valid header give an error, never a panic, and
    /// the framing never returns a frame longer than one maximal APDU.
    #[test]
    fn random_octets_never_panic(bytes in octets()) {
        let _ = Asdu::decode(&bytes);
        let _ = Apdu::decode(&bytes);
        let _ = AsduHeader::decode(&bytes);
        let mut decoder = FrameDecoder::new();
        let mut input = bytes.as_slice();
        while let Ok(Some(frame)) = decoder.next_frame(&mut input) {
            prop_assert!(frame.len() <= MAX_FRAME_OCTETS);
            let _ = Apdu::decode(&frame);
        }
    }

    /// Valid APDUs with octets changed or cut: decoding never panics.
    #[test]
    fn mutated_frames_never_panic(bytes in mutated_apdu()) {
        let _ = Apdu::decode(&bytes);
        let _ = frames_of(&[&bytes]);
    }

    /// Frames cut at arbitrary points, and concatenated, come out of the
    /// decoder unchanged and in order, and each decodes to its APDU.
    #[test]
    fn frames_split_anywhere_come_out_whole(
        apdus in vec(apdu(), 1..=5),
        cuts in vec(any::<usize>(), 0..=8),
    ) {
        let frames: Vec<Vec<u8>> = apdus
            .iter()
            .map(|apdu| apdu.to_vec().expect("generated APDUs encode"))
            .collect();
        let stream = frames.concat();
        let mut points: Vec<usize> = cuts.iter().map(|cut| cut % (stream.len() + 1)).collect();
        points.sort_unstable();
        points.push(stream.len());

        let mut chunks = Vec::new();
        let mut start = 0;
        for end in points {
            let chunk = stream.get(start..end).expect("cut points are in range");
            chunks.push(chunk);
            start = end;
        }
        let decoded = frames_of(&chunks);
        prop_assert_eq!(decoded.clone(), Ok(frames));
        let apdus_back: Result<Vec<Apdu>, _> = decoded
            .expect("framing is valid")
            .iter()
            .map(|frame| Apdu::decode(frame))
            .collect();
        prop_assert_eq!(apdus_back, Ok(apdus));
    }
}

/// The generators reach what the properties claim to test: every in-profile
/// type, both addressing forms, and the file segment. A property that never
/// sees a type would pass without checking it.
#[test]
fn generators_reach_every_in_profile_type_and_both_forms() {
    let mut runner = TestRunner::deterministic();
    let strategy = asdu();
    let mut types = HashSet::new();
    let mut sequences = 0;
    let mut individuals = 0;
    for _ in 0..10_000 {
        let value = strategy.new_tree(&mut runner).expect("a tree").current();
        types.insert(value.type_id());
        if value.body.is_sequence() {
            sequences += 1;
        } else {
            individuals += 1;
        }
    }
    let in_profile = TypeId::ALL.iter().filter(|t| t.in_profile()).count();
    assert_eq!(
        types.len(),
        in_profile,
        "every in-profile type is generated"
    );
    assert!(sequences > 0 && individuals > 0, "both forms are generated");
}
