// SPDX-FileCopyrightText: 2026 The igs-iec104 contributors
//
// SPDX-License-Identifier: Apache-2.0

//! Handshakes of the rustls backend, run in memory between a station's client and server
//! connections. The certificates are the test material of `tests/fixtures/tls`, generated by
//! `generate.sh` there.

use std::sync::{Arc, Mutex};

use rustls::pki_types::ServerName;
use rustls::version::TLS13;
use rustls::{
    ClientConfig, ClientConnection, ConnectionCommon, Error as RustlsError, ServerConnection,
};

use super::*;
use crate::tls::events::{SecurityEvent, SecurityEvents};
use crate::tls::profile;
use crate::tls::settings::TlsSettings;

macro_rules! fixture {
    ($name:literal) => {
        include_bytes!(concat!("../../../tests/fixtures/tls/", $name)).as_slice()
    };
}

/// Keeps the events it receives, for the assertions.
#[derive(Default)]
struct Recorder(Mutex<Vec<SecurityEvent>>);

impl Recorder {
    fn seen(&self) -> Vec<SecurityEvent> {
        self.0
            .lock()
            .map(|events| events.clone())
            .unwrap_or_default()
    }
}

impl SecurityEvents for Recorder {
    fn raise(&self, event: SecurityEvent, _detail: &str) {
        if let Ok(mut events) = self.0.lock() {
            events.push(event);
        }
    }
}

/// One station: its events and its backend.
struct Station {
    events: Arc<Recorder>,
    backend: RustlsBackend,
}

fn trust() -> TrustAnchors {
    trust_anchors_from_pem(fixture!("roots.pem")).expect("the five test roots")
}

/// A station with the certificate and key `(certificate, key)`, the revocation lists `crls`, and
/// the TLS 1.3 switch `tls13`.
fn station(certificate: &[u8], key: &[u8], crls: Vec<Vec<u8>>, tls13: bool) -> Station {
    let events = Arc::new(Recorder::default());
    let identity =
        identity_from_pem(events.as_ref(), certificate, key).expect("the fixture is an identity");
    let shared: Arc<dyn SecurityEvents> = events.clone();
    let settings = TlsSettings::new(identity, trust(), shared)
        .with_revocation(crls)
        .with_tls13(tls13);
    let backend = RustlsBackend::new(&settings).expect("the settings are valid");
    Station { events, backend }
}

fn crl() -> Vec<Vec<u8>> {
    revocation_from_pem(fixture!("crl.pem")).expect("the test CRL")
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Side {
    Client,
    Server,
}

/// Feeds the bytes of one flight to a connection, and processes them.
fn feed<D>(connection: &mut ConnectionCommon<D>, mut bytes: &[u8]) -> Result<(), RustlsError> {
    while !bytes.is_empty() {
        connection
            .read_tls(&mut bytes)
            .map_err(|error| RustlsError::General(error.to_string()))?;
        connection.process_new_packets()?;
    }
    Ok(())
}

/// Runs the handshake between the two connections, in memory, until both finish or one fails.
/// The error names the side that failed.
fn handshake(
    client: &mut ClientConnection,
    server: &mut ServerConnection,
) -> Result<(), (Side, RustlsError)> {
    for _ in 0..64 {
        if !client.is_handshaking() && !server.is_handshaking() {
            return Ok(());
        }
        while client.wants_write() {
            let mut flight = Vec::new();
            client
                .write_tls(&mut flight)
                .expect("a vector takes every byte");
            feed(&mut *server, &flight).map_err(|error| (Side::Server, error))?;
        }
        while server.wants_write() {
            let mut flight = Vec::new();
            server
                .write_tls(&mut flight)
                .expect("a vector takes every byte");
            feed(&mut *client, &flight).map_err(|error| (Side::Client, error))?;
        }
    }
    Err((Side::Client, RustlsError::HandshakeNotComplete))
}

/// Connects the client station to the server station, and runs the handshake.
fn connect(
    client: &Station,
    server: &Station,
) -> Result<(ClientConnection, ServerConnection), (Side, RustlsError)> {
    let name = ServerName::try_from("localhost").expect("a DNS name");
    let mut client_connection = client
        .backend
        .client_connection(name)
        .expect("a client connection");
    let mut server_connection = server
        .backend
        .server_connection()
        .expect("a server connection");
    handshake(&mut client_connection, &mut server_connection)?;
    Ok((client_connection, server_connection))
}

#[test]
fn a_mutual_handshake_succeeds_with_tls_1_3() {
    let client = station(
        fixture!("client.pem"),
        fixture!("client.key"),
        Vec::new(),
        true,
    );
    let server = station(
        fixture!("server.pem"),
        fixture!("server.key"),
        Vec::new(),
        true,
    );
    let (client_connection, server_connection) = connect(&client, &server).expect("the handshake");

    assert_eq!(
        client_connection.protocol_version(),
        Some(rustls::ProtocolVersion::TLSv1_3)
    );
    let suite = client_connection
        .negotiated_cipher_suite()
        .expect("a suite");
    assert!(profile::allows(u16::from(suite.suite())));
    assert!(
        server_connection.peer_certificates().is_some(),
        "the server has the client certificate"
    );

    raise_handshake_success(client.events.as_ref());
    raise_handshake_success(server.events.as_ref());
    assert_eq!(
        client.events.seen(),
        vec![SecurityEvent::TlsHandshakeSuccess]
    );
    assert_eq!(
        server.events.seen(),
        vec![SecurityEvent::TlsHandshakeSuccess]
    );
}

#[test]
fn a_mutual_handshake_succeeds_with_tls_1_2_when_tls_1_3_is_disabled() {
    let client = station(
        fixture!("client.pem"),
        fixture!("client.key"),
        Vec::new(),
        false,
    );
    let server = station(
        fixture!("server.pem"),
        fixture!("server.key"),
        Vec::new(),
        false,
    );
    let (client_connection, _server_connection) = connect(&client, &server).expect("the handshake");

    assert_eq!(
        client_connection.protocol_version(),
        Some(rustls::ProtocolVersion::TLSv1_2)
    );
    let suite = client_connection
        .negotiated_cipher_suite()
        .expect("a suite");
    assert!(profile::allows(u16::from(suite.suite())));
}

#[test]
fn a_client_without_a_certificate_is_refused_and_the_server_raises_no_peer_certificate() {
    let server = station(
        fixture!("server.pem"),
        fixture!("server.key"),
        Vec::new(),
        true,
    );
    // A client that presents no certificate: rustls has no client authentication configured.
    let roots = Arc::new(root_store(&trust()).expect("the roots"));
    let anonymous = ClientConfig::builder_with_provider(Arc::new(profile_provider()))
        .with_protocol_versions(&[&TLS13])
        .expect("TLS 1.3")
        .with_root_certificates(roots)
        .with_no_client_auth();
    let name = ServerName::try_from("localhost").expect("a DNS name");
    let mut client = ClientConnection::new(Arc::new(anonymous), name).expect("a connection");
    let mut server_connection = server.backend.server_connection().expect("a connection");

    let (side, error) = handshake(&mut client, &mut server_connection)
        .expect_err("the handshake must fail without a client certificate");
    assert_eq!(side, Side::Server);
    raise_handshake_failure(server.events.as_ref(), &error);
    assert_eq!(server.events.seen(), vec![SecurityEvent::NoPeerCertificate]);
}

#[test]
fn a_client_certificate_from_an_unknown_ca_is_refused_and_the_server_raises_no_ca_match() {
    let client = station(
        fixture!("rogue_client.pem"),
        fixture!("rogue_client.key"),
        Vec::new(),
        true,
    );
    let server = station(
        fixture!("server.pem"),
        fixture!("server.key"),
        Vec::new(),
        true,
    );
    let (side, error) = connect(&client, &server).expect_err("an unknown CA is refused");
    assert_eq!(side, Side::Server);
    raise_handshake_failure(server.events.as_ref(), &error);
    assert_eq!(server.events.seen(), vec![SecurityEvent::NoCaMatch]);
}

#[test]
fn an_expired_client_certificate_is_refused_and_the_server_raises_the_expiry() {
    let client = station(
        fixture!("expired_client.pem"),
        fixture!("expired_client.key"),
        Vec::new(),
        true,
    );
    let server = station(
        fixture!("server.pem"),
        fixture!("server.key"),
        Vec::new(),
        true,
    );
    let (side, error) = connect(&client, &server).expect_err("an expired certificate is refused");
    assert_eq!(side, Side::Server);
    raise_handshake_failure(server.events.as_ref(), &error);
    assert_eq!(
        server.events.seen(),
        vec![SecurityEvent::CertificateExpired]
    );
}

#[test]
fn a_revoked_client_certificate_is_refused_with_the_crl_and_both_events_are_raised() {
    let client = station(
        fixture!("revoked_client.pem"),
        fixture!("revoked_client.key"),
        Vec::new(),
        true,
    );
    let server = station(fixture!("server.pem"), fixture!("server.key"), crl(), true);
    let (side, error) = connect(&client, &server).expect_err("a revoked certificate is refused");
    assert_eq!(side, Side::Server);
    raise_handshake_failure(server.events.as_ref(), &error);
    assert_eq!(
        server.events.seen(),
        vec![
            SecurityEvent::CertificateRevoked,
            SecurityEvent::RevokedSessionClosed
        ]
    );
}

#[test]
fn the_same_certificate_is_accepted_without_the_crl() {
    // The control for the test above: the refusal comes from the revocation list, not from the
    // certificate itself.
    let client = station(
        fixture!("revoked_client.pem"),
        fixture!("revoked_client.key"),
        Vec::new(),
        true,
    );
    let server = station(
        fixture!("server.pem"),
        fixture!("server.key"),
        Vec::new(),
        true,
    );
    assert!(connect(&client, &server).is_ok());
}

#[test]
fn a_server_certificate_above_the_size_limit_is_refused_by_the_client() {
    let client = station(
        fixture!("client.pem"),
        fixture!("client.key"),
        Vec::new(),
        true,
    );
    let server = station(
        fixture!("big_server.pem"),
        fixture!("big_server.key"),
        Vec::new(),
        true,
    );
    let (side, error) = connect(&client, &server).expect_err("an oversized certificate is refused");
    assert_eq!(side, Side::Client);
    raise_handshake_failure(client.events.as_ref(), &error);
    // The size check raised its own event, and the error adds none.
    assert_eq!(
        client.events.seen(),
        vec![SecurityEvent::CertificateSizeExceeded]
    );
}

#[test]
fn an_identity_that_does_not_parse_raises_no_local_certificate() {
    let events = Recorder::default();
    let result = identity_from_pem(&events, b"not a certificate", fixture!("server.key"));
    assert!(matches!(result, Err(TlsError::Identity(_))));
    assert_eq!(events.seen(), vec![SecurityEvent::NoLocalCertificate]);
}

#[test]
fn a_key_that_does_not_match_its_certificate_raises_no_local_certificate() {
    let events = Arc::new(Recorder::default());
    let identity = identity_from_pem(
        events.as_ref(),
        fixture!("server.pem"),
        fixture!("client.key"),
    )
    .expect("both parse");
    let shared: Arc<dyn SecurityEvents> = events.clone();
    let settings = TlsSettings::new(identity, trust(), shared);
    assert!(matches!(
        RustlsBackend::new(&settings),
        Err(TlsError::Identity(_))
    ));
    assert_eq!(events.seen(), vec![SecurityEvent::NoLocalCertificate]);
}

#[test]
fn the_offered_suites_are_the_profile_suites_and_no_null_or_cbc_suite() {
    let provider = profile_provider();
    assert!(!provider.cipher_suites.is_empty());
    for suite in &provider.cipher_suites {
        let name = format!("{:?}", suite.suite());
        assert!(
            profile::allows(u16::from(suite.suite())),
            "{name} is not in the profile"
        );
        assert!(
            !name.contains("NULL") && !name.contains("CBC"),
            "{name} is excluded"
        );
    }
    // The mandatory suites that rustls implements are offered. The CBC and DHE suites, and the
    // CCM suite of TLS 1.3, are not: rustls has none of them (see the module documentation).
    let offered: Vec<String> = provider
        .cipher_suites
        .iter()
        .map(|suite| format!("{:?}", suite.suite()))
        .collect();
    assert!(offered
        .iter()
        .any(|name| name.contains("TLS13_AES_128_GCM_SHA256")));
    assert!(offered
        .iter()
        .any(|name| name.contains("ECDHE_ECDSA_WITH_AES_128_GCM_SHA256")));
    assert!(offered
        .iter()
        .any(|name| name.contains("ECDHE_RSA_WITH_AES_128_GCM_SHA256")));
}

#[test]
fn only_the_listed_groups_are_offered() {
    let provider = profile_provider();
    let groups: Vec<u16> = provider
        .kx_groups
        .iter()
        .map(|group| u16::from(group.name()))
        .collect();
    assert!(groups.contains(&23), "secp256r1 is mandatory");
    assert!(groups.iter().all(|group| profile::allows_group(*group)));
}

#[test]
fn the_five_trust_anchors_of_clause_6_4_1_load() {
    assert_eq!(trust().roots().len(), 5);
    let events = Arc::new(Recorder::default());
    let identity = identity_from_pem(
        events.as_ref(),
        fixture!("server.pem"),
        fixture!("server.key"),
    )
    .expect("the identity");
    let shared: Arc<dyn SecurityEvents> = events.clone();
    assert!(RustlsBackend::new(&TlsSettings::new(identity, trust(), shared)).is_ok());
}
