// SPDX-FileCopyrightText: 2026 The igs-iec104 contributors
//
// SPDX-License-Identifier: Apache-2.0

//! The TLS option of the client and of the server, over loopback (task X1). The certificates are
//! the test material of `tests/fixtures/tls`, generated by `generate.sh` there.

#![cfg(feature = "rustls")]
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]

use std::net::SocketAddr;
use std::sync::{Arc, Mutex};
use std::time::Duration;

use igs_iec104::client::{Client, ClientConfig, Event};
use igs_iec104::process_image::PointValue;
use igs_iec104::server::{Handler, Operation, Refusal, Server, ServerConfig, ServerHandle};
use igs_iec104::tls::events::{SecurityEvent, SecurityEvents};
use igs_iec104::tls::rustls_backend::{identity_from_pem, trust_anchors_from_pem, RustlsBackend};
use igs_iec104::tls::settings::TlsSettings;
use igs_iec104::tls::Secure;
use igs_iec104::{Delivery, TransportError};
use igs_iec104_codec::asdu::Body;
use igs_iec104_codec::elements::{Qoi, QualityFlags, Siq};
use igs_iec104_codec::header::{cause, CommonAddress, InformationObjectAddress};
use igs_iec104_link::{Parameters, TransferState};
use rustls::pki_types::pem::PemObject;
use rustls::pki_types::{CertificateDer, ServerName};
use tokio::net::{TcpListener, TcpStream};
use tokio::time::{sleep, timeout};

const ROOTS: &[u8] = include_bytes!("fixtures/tls/roots.pem");
const SERVER_CERTIFICATE: &[u8] = include_bytes!("fixtures/tls/server.pem");
const SERVER_KEY: &[u8] = include_bytes!("fixtures/tls/server.key");
const CLIENT_CERTIFICATE: &[u8] = include_bytes!("fixtures/tls/client.pem");
const CLIENT_KEY: &[u8] = include_bytes!("fixtures/tls/client.key");

const STATION: u16 = 1;

/// Keeps the security events it receives.
#[derive(Default)]
struct Recorder(Mutex<Vec<SecurityEvent>>);

impl Recorder {
    fn seen(&self) -> Vec<SecurityEvent> {
        self.0
            .lock()
            .map(|events| events.clone())
            .unwrap_or_default()
    }
}

impl SecurityEvents for Recorder {
    fn raise(&self, event: SecurityEvent, _detail: &str) {
        if let Ok(mut events) = self.0.lock() {
            events.push(event);
        }
    }
}

/// The TLS backend of one station, with its identity and the five test roots.
fn backend(events: &Arc<Recorder>, certificate: &[u8], key: &[u8]) -> Secure {
    let shared: Arc<dyn SecurityEvents> = events.clone();
    let identity = identity_from_pem(events.as_ref(), certificate, key).expect("the identity");
    let trust = trust_anchors_from_pem(ROOTS).expect("the roots");
    let settings = TlsSettings::new(identity, trust, shared);
    Secure::new(RustlsBackend::new(&settings).expect("the backend"))
}

/// A handler that refuses every command: these tests only interrogate.
struct Refuse;

impl Handler for Refuse {
    fn select(&self, _operation: &Operation) -> Result<(), Refusal> {
        Err(Refusal::Rejected)
    }

    fn execute(&self, _operation: &Operation) -> Result<(), Refusal> {
        Err(Refusal::Rejected)
    }
}

fn address(value: u32) -> InformationObjectAddress {
    InformationObjectAddress::new(value).expect("in range")
}

/// Starts a TLS station with one single-point, and returns its address.
async fn start_station(events: &Arc<Recorder>) -> SocketAddr {
    let config = ServerConfig::new(
        "127.0.0.1:0".parse().expect("an address"),
        CommonAddress::new(STATION),
    )
    .with_tls(backend(events, SERVER_CERTIFICATE, SERVER_KEY));
    let server = Server::bind(config, Refuse)
        .await
        .expect("the station binds");
    let local = server.local_addr().expect("it has an address");
    let handle: ServerHandle = server.handle();
    let value = PointValue::Single(Siq {
        on: true,
        quality: QualityFlags::default(),
    });
    handle
        .add_point(address(1), value, false)
        .expect("the point");
    tokio::spawn(server.run());
    local
}

/// Waits, for at most 10 s, for the first event that `wanted` accepts.
async fn next_until(
    client: &mut Client,
    mut wanted: impl FnMut(&Event) -> bool,
    what: &str,
) -> Event {
    timeout(Duration::from_secs(10), async {
        loop {
            let event = client.next_event().await.expect("the client runs");
            if wanted(&event) {
                return event;
            }
        }
    })
    .await
    .unwrap_or_else(|_| panic!("no {what} within 10 s"))
}

/// Connects a TLS client to the station, and starts the data transfer.
async fn connect(address: SocketAddr, backend: Secure) -> Client {
    let config =
        ClientConfig::new(address, CommonAddress::new(STATION)).with_tls(backend, "localhost");
    let mut client = Client::connect(config);
    next_until(
        &mut client,
        |e| matches!(e, Event::Connected),
        "the connection",
    )
    .await;
    client.start_data_transfer().await.expect("the client runs");
    next_until(
        &mut client,
        |e| {
            matches!(
                e,
                Event::Delivery(Delivery::Transfer(TransferState::Started))
            )
        },
        "the start",
    )
    .await;
    client
}

/// Polls a recorder until it holds `wanted`, for at most 5 s.
async fn raised(events: &Recorder, wanted: SecurityEvent) -> bool {
    timeout(Duration::from_secs(5), async {
        loop {
            if events.seen().contains(&wanted) {
                return true;
            }
            sleep(Duration::from_millis(10)).await;
        }
    })
    .await
    .unwrap_or(false)
}

/// The root certificates of the test material, for the raw clients below.
fn roots() -> rustls::RootCertStore {
    let mut store = rustls::RootCertStore::empty();
    for der in CertificateDer::pem_slice_iter(ROOTS) {
        store.add(der.expect("a root")).expect("a root is accepted");
    }
    store
}

#[tokio::test]
async fn the_station_answers_an_interrogation_over_tls_and_both_sides_raise_the_notice() {
    let server_events = Arc::new(Recorder::default());
    let client_events = Arc::new(Recorder::default());
    let station = start_station(&server_events).await;

    let mut client = connect(
        station,
        backend(&client_events, CLIENT_CERTIFICATE, CLIENT_KEY),
    )
    .await;
    client
        .interrogate(Qoi::STATION)
        .await
        .expect("the client runs");
    next_until(
        &mut client,
        |e| {
            matches!(e, Event::Delivery(Delivery::Asdu(asdu))
                if asdu.cot.cause() == cause::INTERROGATED_STATION
                    && matches!(asdu.body, Body::M_SP_NA_1(_)))
        },
        "the answer with the point",
    )
    .await;

    assert!(client_events
        .seen()
        .contains(&SecurityEvent::TlsHandshakeSuccess));
    assert!(raised(&server_events, SecurityEvent::TlsHandshakeSuccess).await);
}

#[tokio::test]
async fn a_client_without_a_certificate_is_refused_and_the_station_raises_no_peer_certificate() {
    let server_events = Arc::new(Recorder::default());
    let station = start_station(&server_events).await;

    // A client with no client certificate: the station requires one (clause 6.4.3).
    let config = rustls::ClientConfig::builder_with_provider(Arc::new(
        rustls::crypto::ring::default_provider(),
    ))
    .with_protocol_versions(&[&rustls::version::TLS13])
    .expect("TLS 1.3")
    .with_root_certificates(Arc::new(roots()))
    .with_no_client_auth();
    let connector = tokio_rustls::TlsConnector::from(Arc::new(config));
    let tcp = TcpStream::connect(station)
        .await
        .expect("the TCP connection");
    let name = ServerName::try_from("localhost").expect("a name");
    // In TLS 1.3 the client may finish its side before the station refuses the certificate.
    let _ = connector.connect(name, tcp).await;

    assert!(raised(&server_events, SecurityEvent::NoPeerCertificate).await);
}

#[tokio::test]
async fn a_client_that_proposes_only_suites_outside_the_profile_is_refused() {
    let server_events = Arc::new(Recorder::default());
    let station = start_station(&server_events).await;

    // TLS 1.2 with ChaCha20 only: the profile does not list that suite (table 9).
    let mut provider = rustls::crypto::ring::default_provider();
    provider
        .cipher_suites
        .retain(|suite| format!("{:?}", suite.suite()).contains("CHACHA20"));
    provider
        .cipher_suites
        .retain(|suite| format!("{:?}", suite.suite()).contains("TLS_ECDHE"));
    let config = rustls::ClientConfig::builder_with_provider(Arc::new(provider))
        .with_protocol_versions(&[&rustls::version::TLS12])
        .expect("TLS 1.2")
        .with_root_certificates(Arc::new(roots()))
        .with_no_client_auth();
    let connector = tokio_rustls::TlsConnector::from(Arc::new(config));
    let tcp = TcpStream::connect(station)
        .await
        .expect("the TCP connection");
    let name = ServerName::try_from("localhost").expect("a name");

    assert!(
        connector.connect(name, tcp).await.is_err(),
        "no common suite, so no session"
    );
    assert!(!server_events
        .seen()
        .contains(&SecurityEvent::TlsHandshakeSuccess));
}

#[tokio::test]
async fn a_tls_client_reports_a_failed_connection_to_a_plain_station() {
    // A station that accepts TCP and then closes it: the TLS handshake cannot succeed.
    let listener = TcpListener::bind("127.0.0.1:0").await.expect("binds");
    let plain = listener.local_addr().expect("an address");
    tokio::spawn(async move {
        loop {
            if let Ok((stream, _peer)) = listener.accept().await {
                drop(stream);
            }
        }
    });

    let events = Arc::new(Recorder::default());
    let config = ClientConfig::new(plain, CommonAddress::new(STATION)).with_tls(
        backend(&events, CLIENT_CERTIFICATE, CLIENT_KEY),
        "localhost",
    );
    let mut client = Client::connect(config);
    let event = next_until(
        &mut client,
        |e| matches!(e, Event::ConnectFailed(_)),
        "a failed connection",
    )
    .await;
    assert!(
        matches!(event, Event::ConnectFailed(TransportError::Secure(_))),
        "the failure is a TLS failure: {event:?}"
    );
}

#[tokio::test]
async fn a_station_that_never_answers_the_handshake_is_given_up_after_t0() {
    // A station that accepts TCP and never speaks: the handshake waits until t0 expires.
    let listener = TcpListener::bind("127.0.0.1:0").await.expect("binds");
    let silent = listener.local_addr().expect("an address");
    tokio::spawn(async move {
        let mut held = Vec::new();
        loop {
            if let Ok((stream, _peer)) = listener.accept().await {
                held.push(stream);
            }
        }
    });

    let events = Arc::new(Recorder::default());
    let parameters = Parameters {
        t0: Duration::from_secs(1),
        ..Parameters::default()
    };
    let config = ClientConfig::new(silent, CommonAddress::new(STATION))
        .with_parameters(parameters)
        .expect("valid parameters")
        .with_tls(
            backend(&events, CLIENT_CERTIFICATE, CLIENT_KEY),
            "localhost",
        );
    let mut client = Client::connect(config);
    let event = next_until(
        &mut client,
        |e| matches!(e, Event::ConnectFailed(_)),
        "the handshake time-out",
    )
    .await;
    assert!(
        matches!(
            event,
            Event::ConnectFailed(TransportError::HandshakeTimeout)
        ),
        "the handshake times out: {event:?}"
    );
}
