// SPDX-FileCopyrightText: 2026 The igs-iec104 contributors
//
// SPDX-License-Identifier: Apache-2.0

//! The OpenSSL backend over loopback sockets (task X1, feature `openssl`). The certificates are the
//! test material of `tests/fixtures/tls`, generated by `generate.sh` there.

#![cfg(feature = "openssl")]
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects
)]

use std::net::SocketAddr;
use std::pin::Pin;
use std::sync::{Arc, Mutex};
use std::time::Duration;

use igs_iec104::client::{Client, ClientConfig, Event};
use igs_iec104::process_image::PointValue;
use igs_iec104::server::{Handler, Operation, Refusal, Server, ServerConfig, ServerHandle};
use igs_iec104::tls::events::{SecurityEvent, SecurityEvents};
use igs_iec104::tls::openssl_backend::OpensslBackend;
use igs_iec104::tls::profile::{
    Support, GROUPS, MANDATORY_SIGNATURE_ALGORITHMS, TLS12_SUITES, TLS13_SUITES,
};
use igs_iec104::tls::settings::{Identity, TlsSettings, TrustAnchors};
use igs_iec104::tls::Secure;
use igs_iec104::Delivery;
use igs_iec104_codec::asdu::Body;
use igs_iec104_codec::elements::{Qoi, QualityFlags, Siq};
use igs_iec104_codec::header::{cause, CommonAddress, InformationObjectAddress};
use igs_iec104_link::TransferState;
use openssl::ssl::{Ssl, SslConnector, SslMethod, SslVerifyMode, SslVersion};
use openssl::x509::store::X509StoreBuilder;
use openssl::x509::X509;
use tokio::net::TcpStream;
use tokio::time::{sleep, timeout};
use tokio_openssl::SslStream;

const ROOTS: &[u8] = include_bytes!("fixtures/tls/roots.pem");
const SERVER_CERTIFICATE: &[u8] = include_bytes!("fixtures/tls/server.pem");
const SERVER_KEY: &[u8] = include_bytes!("fixtures/tls/server.key");
const CLIENT_CERTIFICATE: &[u8] = include_bytes!("fixtures/tls/client.pem");
const CLIENT_KEY: &[u8] = include_bytes!("fixtures/tls/client.key");
const RSA_SERVER_CERTIFICATE: &[u8] = include_bytes!("fixtures/tls/rsa_server.pem");
const RSA_SERVER_KEY: &[u8] = include_bytes!("fixtures/tls/rsa_server.key");
const PSS_SERVER_CERTIFICATE: &[u8] = include_bytes!("fixtures/tls/pss_server.pem");
const PSS_SERVER_KEY: &[u8] = include_bytes!("fixtures/tls/pss_server.key");
const BIG_SERVER_CERTIFICATE: &[u8] = include_bytes!("fixtures/tls/big_server.pem");
const BIG_SERVER_KEY: &[u8] = include_bytes!("fixtures/tls/big_server.key");
const EXPIRED_CERTIFICATE: &[u8] = include_bytes!("fixtures/tls/expired_client.pem");
const EXPIRED_KEY: &[u8] = include_bytes!("fixtures/tls/expired_client.key");
const REVOKED_CERTIFICATE: &[u8] = include_bytes!("fixtures/tls/revoked_client.pem");
const REVOKED_KEY: &[u8] = include_bytes!("fixtures/tls/revoked_client.key");
const ROGUE_CERTIFICATE: &[u8] = include_bytes!("fixtures/tls/rogue_client.pem");
const ROGUE_KEY: &[u8] = include_bytes!("fixtures/tls/rogue_client.key");
const CRL: &[u8] = include_bytes!("fixtures/tls/crl.pem");

const STATION: u16 = 1;

/// Keeps the security events it receives.
#[derive(Default)]
struct Recorder(Mutex<Vec<SecurityEvent>>);

impl Recorder {
    fn seen(&self) -> Vec<SecurityEvent> {
        self.0
            .lock()
            .map(|events| events.clone())
            .unwrap_or_default()
    }
}

impl SecurityEvents for Recorder {
    fn raise(&self, event: SecurityEvent, _detail: &str) {
        if let Ok(mut events) = self.0.lock() {
            events.push(event);
        }
    }
}

/// Gives a raw client the test client certificate: the station requires one (clause 6.4.3).
fn with_client_identity(builder: &mut openssl::ssl::SslConnectorBuilder) {
    let certificate = X509::from_pem(CLIENT_CERTIFICATE).expect("the client certificate");
    let key = openssl::pkey::PKey::private_key_from_pem(CLIENT_KEY).expect("the client key");
    builder
        .set_certificate(&certificate)
        .expect("the certificate");
    builder.set_private_key(&key).expect("the key");
}

/// The DER of every PEM certificate in `pem`.
fn der_list(pem: &[u8]) -> Vec<Vec<u8>> {
    X509::stack_from_pem(pem)
        .expect("certificates")
        .iter()
        .map(|certificate| certificate.to_der().expect("DER"))
        .collect()
}

/// The DER of a PEM file with one certificate, and of its key.
fn der_pair(certificate: &[u8], key: &[u8]) -> (Vec<Vec<u8>>, Vec<u8>) {
    let chain = der_list(certificate);
    let key = openssl::pkey::PKey::private_key_from_pem(key)
        .expect("a key")
        .private_key_to_der()
        .expect("DER of the key");
    (chain, key)
}

/// The OpenSSL backend of one station, with its identity, the five test roots, the CRLs, and the
/// TLS 1.3 switch.
fn backend(
    events: &Arc<Recorder>,
    certificate: &[u8],
    key: &[u8],
    crls: Vec<Vec<u8>>,
    tls13: bool,
) -> Secure {
    let (chain, key) = der_pair(certificate, key);
    let shared: Arc<dyn SecurityEvents> = events.clone();
    let identity = Identity::new(chain, key, events.as_ref()).expect("the identity");
    let trust = TrustAnchors::new(der_list(ROOTS)).expect("the roots");
    let settings = TlsSettings::new(identity, trust, shared)
        .with_revocation(crls)
        .with_tls13(tls13);
    Secure::new(OpensslBackend::new(&settings).expect("the backend"))
}

fn crl() -> Vec<Vec<u8>> {
    der_list_crl(CRL)
}

fn der_list_crl(pem: &[u8]) -> Vec<Vec<u8>> {
    let crl = openssl::x509::X509Crl::from_pem(pem).expect("a CRL");
    vec![crl.to_der().expect("DER")]
}

/// A handler that refuses every command: these tests only interrogate.
struct Refuse;

impl Handler for Refuse {
    fn select(&self, _operation: &Operation) -> Result<(), Refusal> {
        Err(Refusal::Rejected)
    }

    fn execute(&self, _operation: &Operation) -> Result<(), Refusal> {
        Err(Refusal::Rejected)
    }
}

/// Starts a station with one single-point, and returns its address.
async fn start_station(events: &Arc<Recorder>, tls13: bool) -> SocketAddr {
    let config = ServerConfig::new(
        "127.0.0.1:0".parse().expect("an address"),
        CommonAddress::new(STATION),
    )
    .with_tls(backend(
        events,
        SERVER_CERTIFICATE,
        SERVER_KEY,
        crl(),
        tls13,
    ));
    let server = Server::bind(config, Refuse)
        .await
        .expect("the station binds");
    let local = server.local_addr().expect("it has an address");
    let handle: ServerHandle = server.handle();
    let value = PointValue::Single(Siq {
        on: true,
        quality: QualityFlags::default(),
    });
    handle
        .add_point(
            InformationObjectAddress::new(1).expect("in range"),
            value,
            false,
        )
        .expect("the point");
    tokio::spawn(server.run());
    local
}

/// Waits, for at most 10 s, for the first event that `wanted` accepts.
async fn next_until(
    client: &mut Client,
    mut wanted: impl FnMut(&Event) -> bool,
    what: &str,
) -> Event {
    timeout(Duration::from_secs(10), async {
        loop {
            let event = client.next_event().await.expect("the client runs");
            if wanted(&event) {
                return event;
            }
        }
    })
    .await
    .unwrap_or_else(|_| panic!("no {what} within 10 s"))
}

/// Connects a TLS client to the station, and starts the data transfer.
async fn connect(address: SocketAddr, backend: Secure) -> Client {
    let config =
        ClientConfig::new(address, CommonAddress::new(STATION)).with_tls(backend, "localhost");
    let mut client = Client::connect(config);
    next_until(
        &mut client,
        |e| matches!(e, Event::Connected),
        "the connection",
    )
    .await;
    client.start_data_transfer().await.expect("the client runs");
    next_until(
        &mut client,
        |e| {
            matches!(
                e,
                Event::Delivery(Delivery::Transfer(TransferState::Started))
            )
        },
        "the start",
    )
    .await;
    client
}

/// Polls a recorder until it holds `wanted`, for at most 5 s.
async fn raised(events: &Recorder, wanted: SecurityEvent) -> bool {
    timeout(Duration::from_secs(5), async {
        loop {
            if events.seen().contains(&wanted) {
                return true;
            }
            sleep(Duration::from_millis(10)).await;
        }
    })
    .await
    .unwrap_or(false)
}

/// A raw OpenSSL client, offering only what the test sets, with the test roots. It returns the
/// standard name of the suite that was negotiated, or the error of the handshake.
async fn raw_client(
    address: SocketAddr,
    configure: impl FnOnce(&mut openssl::ssl::SslConnectorBuilder),
) -> Result<(String, Option<String>), String> {
    let mut builder = SslConnector::builder(SslMethod::tls_client()).map_err(|e| e.to_string())?;
    let mut store = X509StoreBuilder::new().map_err(|e| e.to_string())?;
    for root in X509::stack_from_pem(ROOTS).map_err(|e| e.to_string())? {
        store.add_cert(root).map_err(|e| e.to_string())?;
    }
    builder
        .set_verify_cert_store(store.build())
        .map_err(|e| e.to_string())?;
    builder.set_verify(SslVerifyMode::PEER);
    configure(&mut builder);
    let connector = builder.build();
    let ssl: Ssl = connector
        .configure()
        .map_err(|e| e.to_string())?
        .into_ssl("localhost")
        .map_err(|e| e.to_string())?;
    let tcp = TcpStream::connect(address)
        .await
        .map_err(|e| e.to_string())?;
    let mut stream = SslStream::new(ssl, tcp).map_err(|e| e.to_string())?;
    Pin::new(&mut stream)
        .connect()
        .await
        .map_err(|e| e.to_string())?;
    let cipher = stream.ssl().current_cipher().expect("a cipher");
    Ok((
        cipher.standard_name().unwrap_or_default().to_string(),
        Some(cipher.version().to_string()),
    ))
}

#[tokio::test]
async fn the_station_answers_an_interrogation_over_tls_13_and_raises_the_notice() {
    let server_events = Arc::new(Recorder::default());
    let client_events = Arc::new(Recorder::default());
    let station = start_station(&server_events, true).await;

    let mut client = connect(
        station,
        backend(&client_events, CLIENT_CERTIFICATE, CLIENT_KEY, crl(), true),
    )
    .await;
    client
        .interrogate(Qoi::STATION)
        .await
        .expect("the client runs");
    next_until(
        &mut client,
        |e| {
            matches!(e, Event::Delivery(Delivery::Asdu(asdu))
                if asdu.cot.cause() == cause::INTERROGATED_STATION
                    && matches!(asdu.body, Body::M_SP_NA_1(_)))
        },
        "the answer with the point",
    )
    .await;
    assert!(client_events
        .seen()
        .contains(&SecurityEvent::TlsHandshakeSuccess));
    assert!(raised(&server_events, SecurityEvent::TlsHandshakeSuccess).await);
}

#[tokio::test]
async fn the_station_answers_over_tls_12_when_tls_13_is_disabled() {
    let server_events = Arc::new(Recorder::default());
    let client_events = Arc::new(Recorder::default());
    let station = start_station(&server_events, false).await;

    let mut client = connect(
        station,
        backend(&client_events, CLIENT_CERTIFICATE, CLIENT_KEY, crl(), false),
    )
    .await;
    client
        .interrogate(Qoi::STATION)
        .await
        .expect("the client runs");
    next_until(
        &mut client,
        |e| matches!(e, Event::Delivery(Delivery::Asdu(asdu)) if asdu.cot.cause() == cause::ACTIVATION_TERMINATION),
        "the termination",
    )
    .await;
}

#[tokio::test]
async fn a_client_without_a_certificate_is_refused_and_the_station_raises_no_peer_certificate() {
    let server_events = Arc::new(Recorder::default());
    let station = start_station(&server_events, true).await;

    let _ = raw_client(station, |_builder| {}).await;
    assert!(raised(&server_events, SecurityEvent::NoPeerCertificate).await);
}

#[tokio::test]
async fn a_client_certificate_from_an_unknown_ca_is_refused_and_the_station_raises_no_ca_match() {
    let server_events = Arc::new(Recorder::default());
    let client_events = Arc::new(Recorder::default());
    let station = start_station(&server_events, true).await;
    let client = backend(
        &client_events,
        ROGUE_CERTIFICATE,
        ROGUE_KEY,
        Vec::new(),
        true,
    );
    let _ = connect_once(station, client).await;
    assert!(raised(&server_events, SecurityEvent::NoCaMatch).await);
}

#[tokio::test]
async fn an_expired_client_certificate_is_refused_and_the_station_raises_the_expiry() {
    let server_events = Arc::new(Recorder::default());
    let client_events = Arc::new(Recorder::default());
    let station = start_station(&server_events, true).await;
    let client = backend(
        &client_events,
        EXPIRED_CERTIFICATE,
        EXPIRED_KEY,
        Vec::new(),
        true,
    );
    let _ = connect_once(station, client).await;
    assert!(raised(&server_events, SecurityEvent::CertificateExpired).await);
}

#[tokio::test]
async fn a_revoked_client_certificate_is_refused_with_the_crl_and_both_events_are_raised() {
    let server_events = Arc::new(Recorder::default());
    let client_events = Arc::new(Recorder::default());
    let station = start_station(&server_events, true).await;
    let client = backend(
        &client_events,
        REVOKED_CERTIFICATE,
        REVOKED_KEY,
        Vec::new(),
        true,
    );
    let _ = connect_once(station, client).await;
    assert!(raised(&server_events, SecurityEvent::CertificateRevoked).await);
    assert!(raised(&server_events, SecurityEvent::RevokedSessionClosed).await);
}

#[tokio::test]
async fn the_same_revoked_certificate_is_accepted_without_the_crl() {
    // The control for the test above: the refusal comes from the revocation list.
    let server_events = Arc::new(Recorder::default());
    let client_events = Arc::new(Recorder::default());
    let config = ServerConfig::new(
        "127.0.0.1:0".parse().expect("an address"),
        CommonAddress::new(STATION),
    )
    .with_tls(backend(
        &server_events,
        SERVER_CERTIFICATE,
        SERVER_KEY,
        Vec::new(),
        true,
    ));
    let server = Server::bind(config, Refuse).await.expect("binds");
    let station = server.local_addr().expect("an address");
    tokio::spawn(server.run());
    let client = backend(
        &client_events,
        REVOKED_CERTIFICATE,
        REVOKED_KEY,
        Vec::new(),
        true,
    );
    assert!(connect_once(station, client).await.is_ok());
}

#[tokio::test]
async fn a_server_certificate_above_the_size_limit_is_refused_by_the_client() {
    let client_events = Arc::new(Recorder::default());
    let server_events = Arc::new(Recorder::default());
    let station = start_station_with(&server_events, BIG_SERVER_CERTIFICATE, BIG_SERVER_KEY).await;
    let client = backend(&client_events, CLIENT_CERTIFICATE, CLIENT_KEY, crl(), true);
    let _ = connect_once(station, client).await;
    assert!(raised(&client_events, SecurityEvent::CertificateSizeExceeded).await);
}

/// A station with a given identity, in place of the test server certificate.
async fn start_station_with(events: &Arc<Recorder>, certificate: &[u8], key: &[u8]) -> SocketAddr {
    let config = ServerConfig::new(
        "127.0.0.1:0".parse().expect("an address"),
        CommonAddress::new(STATION),
    )
    .with_tls(backend(events, certificate, key, crl(), true));
    let server = Server::bind(config, Refuse).await.expect("binds");
    let local = server.local_addr().expect("an address");
    tokio::spawn(server.run());
    local
}

/// Connects a client station once and reports whether the session was established, without
/// waiting for a Started event: a refused handshake shows as a failed connection.
async fn connect_once(address: SocketAddr, backend: Secure) -> Result<(), String> {
    let config =
        ClientConfig::new(address, CommonAddress::new(STATION)).with_tls(backend, "localhost");
    let mut client = Client::connect(config);
    let outcome = timeout(Duration::from_secs(5), async {
        loop {
            match client.next_event().await {
                Some(Event::Connected) => {
                    if let Err(error) = client.start_data_transfer().await {
                        return Err(error.to_string());
                    }
                }
                Some(Event::Delivery(Delivery::Transfer(TransferState::Started))) => {
                    return Ok(());
                }
                Some(Event::ConnectFailed(error)) | Some(Event::Disconnected(error)) => {
                    return Err(error.to_string());
                }
                Some(_) => continue,
                None => return Err("the client stopped".to_string()),
            }
        }
    })
    .await;
    match outcome {
        Ok(result) => result,
        Err(_) => Err("no outcome within 5 s".to_string()),
    }
}

#[tokio::test]
async fn the_suites_that_rustls_cannot_offer_are_negotiated() {
    // The static RSA suite needs an RSA key in the station; table 9 lists it as mandatory.
    let server_events = Arc::new(Recorder::default());
    let station = start_station_with(&server_events, RSA_SERVER_CERTIFICATE, RSA_SERVER_KEY).await;
    let (name, _) = raw_client(station, |builder| {
        with_client_identity(builder);
        builder
            .set_max_proto_version(Some(SslVersion::TLS1_2))
            .expect("TLS 1.2");
        builder.set_cipher_list("AES128-SHA256").expect("the suite");
    })
    .await
    .expect("the CBC suite is negotiated");
    assert_eq!(name, "TLS_RSA_WITH_AES_128_CBC_SHA256");

    // The DHE-RSA suite, which also needs the RSA key (table 9).
    let (name, _) = raw_client(station, |builder| {
        with_client_identity(builder);
        builder
            .set_max_proto_version(Some(SslVersion::TLS1_2))
            .expect("TLS 1.2");
        builder.set_groups_list("ffdhe2048").expect("the group");
        builder
            .set_cipher_list("DHE-RSA-AES128-GCM-SHA256")
            .expect("the suite");
    })
    .await
    .expect("the DHE suite is negotiated");
    assert_eq!(name, "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256");

    // The mandatory CCM suite of TLS 1.3 (table 13), offered alone.
    let station = start_station(&server_events, true).await;
    let (name, _) = raw_client(station, |builder| {
        with_client_identity(builder);
        builder
            .set_min_proto_version(Some(SslVersion::TLS1_3))
            .expect("TLS 1.3");
        builder
            .set_ciphersuites("TLS_AES_128_CCM_SHA256")
            .expect("the suite");
    })
    .await
    .expect("the CCM suite is negotiated");
    assert_eq!(name, "TLS_AES_128_CCM_SHA256");
}

#[tokio::test]
async fn the_mandatory_ffdhe_group_of_tls_13_is_negotiated() {
    // The mandatory group ffdhe2048 of TLS 1.3 (table 16), offered alone (clause 8.3.3).
    let server_events = Arc::new(Recorder::default());
    let station = start_station(&server_events, true).await;
    let (name, version) = raw_client(station, |builder| {
        with_client_identity(builder);
        builder
            .set_min_proto_version(Some(SslVersion::TLS1_3))
            .expect("TLS 1.3");
        builder.set_groups_list("ffdhe2048").expect("the group");
    })
    .await
    .expect("the handshake succeeds with ffdhe2048");
    assert!(name.starts_with("TLS_"), "a TLS 1.3 suite: {name}");
    assert_eq!(version.as_deref(), Some("TLSv1.3"));
}

/// The station key that an item of the profile needs.
#[derive(Clone, Copy)]
enum Key {
    /// The ECDSA key of the server certificate.
    Ecdsa,
    /// The RSA key of the RSA server certificate.
    Rsa,
    /// The RSA-PSS key of the PSS server certificate.
    Pss,
}

/// The mandatory TLS 1.2 suites (table 9 of clause 10.5.1): the profile name, the OpenSSL name, the
/// station key and the group that the test offers.
const TLS12_ITEMS: &[(&str, &str, Key, &str)] = &[
    (
        "TLS_RSA_WITH_AES_128_CBC_SHA256",
        "AES128-SHA256",
        Key::Rsa,
        "P-256",
    ),
    (
        "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256",
        "DHE-RSA-AES128-GCM-SHA256",
        Key::Rsa,
        "ffdhe2048",
    ),
    (
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "ECDHE-RSA-AES128-GCM-SHA256",
        Key::Rsa,
        "P-256",
    ),
    (
        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "ECDHE-ECDSA-AES128-GCM-SHA256",
        Key::Ecdsa,
        "P-256",
    ),
];

/// The mandatory TLS 1.3 suites (table 13 of clause 10.6.1), by their names, which OpenSSL shares.
const TLS13_ITEMS: &[&str] = &[
    "TLS_AES_128_GCM_SHA256",
    "TLS_AES_256_GCM_SHA384",
    "TLS_AES_128_CCM_SHA256",
];

/// The mandatory groups (table 16 of clause 10.6.2): the profile name and the OpenSSL name.
const GROUP_ITEMS: &[(&str, &str)] = &[("secp256r1", "P-256"), ("ffdhe2048", "ffdhe2048")];

/// The mandatory signature algorithms (tables 17 and 18 of clause 10.6.2): the profile name, the
/// list the client offers with its own ECDSA scheme (the client certificate is an ECDSA key), and
/// the station key. The scheme is the only one the station's key can use, so the handshake shows
/// that the station signs with it.
const SIGALG_ITEMS: &[(&str, &str, Key)] = &[
    (
        "rsa_pss_rsae_sha256",
        "rsa_pss_rsae_sha256:ecdsa_secp256r1_sha256",
        Key::Rsa,
    ),
    (
        "rsa_pss_pss_sha256",
        "rsa_pss_pss_sha256:ecdsa_secp256r1_sha256",
        Key::Pss,
    ),
    (
        "ecdsa_secp256r1_sha256",
        "ecdsa_secp256r1_sha256",
        Key::Ecdsa,
    ),
];

/// The mandatory signature algorithms that no test negotiates. rsa_pkcs1_sha256 is mandatory for
/// certificates (table 18): it needs a chain whose issuer signs with RSA PKCS#1, and the test root
/// is an ECDSA key. The test checks this list, so that it changes only with the test.
const NOT_NEGOTIATED: &[&str] = &["rsa_pkcs1_sha256"];

#[tokio::test]
async fn every_mandatory_item_of_the_profile_is_negotiated() {
    // Each item is offered alone to a station with the key it needs. The client holds the test
    // client certificate, which the station requires (clause 6.4.3). An item without a row in the
    // tables above panics, so a new mandatory item cannot be left out.
    let events = Arc::new(Recorder::default());
    let ecdsa = start_station_with(&events, SERVER_CERTIFICATE, SERVER_KEY).await;
    let rsa = start_station_with(&events, RSA_SERVER_CERTIFICATE, RSA_SERVER_KEY).await;
    let pss = start_station_with(&events, PSS_SERVER_CERTIFICATE, PSS_SERVER_KEY).await;
    let station = |key: Key| match key {
        Key::Ecdsa => ecdsa,
        Key::Rsa => rsa,
        Key::Pss => pss,
    };

    for suite in TLS12_SUITES
        .iter()
        .filter(|suite| suite.support == Support::Mandatory)
    {
        let Some(&(_, openssl, key, group)) = TLS12_ITEMS.iter().find(|item| item.0 == suite.name)
        else {
            panic!("no test for the mandatory TLS 1.2 suite {}", suite.name);
        };
        let (name, version) = raw_client(station(key), |builder| {
            with_client_identity(builder);
            builder
                .set_max_proto_version(Some(SslVersion::TLS1_2))
                .expect("TLS 1.2");
            builder.set_groups_list(group).expect("the group");
            builder.set_cipher_list(openssl).expect("the suite");
        })
        .await
        .unwrap_or_else(|error| panic!("{} is not negotiated: {error}", suite.name));
        assert_eq!(name, suite.name);
        assert_eq!(version.as_deref(), Some("TLSv1.2"));
    }

    for suite in TLS13_SUITES
        .iter()
        .filter(|suite| suite.support == Support::Mandatory)
    {
        assert!(
            TLS13_ITEMS.contains(&suite.name),
            "no test for the mandatory TLS 1.3 suite {}",
            suite.name
        );
        let (name, version) = raw_client(ecdsa, |builder| {
            with_client_identity(builder);
            builder
                .set_min_proto_version(Some(SslVersion::TLS1_3))
                .expect("TLS 1.3");
            builder.set_ciphersuites(suite.name).expect("the suite");
        })
        .await
        .unwrap_or_else(|error| panic!("{} is not negotiated: {error}", suite.name));
        assert_eq!(name, suite.name);
        assert_eq!(version.as_deref(), Some("TLSv1.3"));
    }

    for group in GROUPS
        .iter()
        .filter(|group| group.support == Support::Mandatory)
    {
        let Some(&(_, openssl)) = GROUP_ITEMS.iter().find(|item| item.0 == group.name) else {
            panic!("no test for the mandatory group {}", group.name);
        };
        let (_, version) = raw_client(ecdsa, |builder| {
            with_client_identity(builder);
            builder
                .set_min_proto_version(Some(SslVersion::TLS1_3))
                .expect("TLS 1.3");
            builder.set_groups_list(openssl).expect("the group");
        })
        .await
        .unwrap_or_else(|error| panic!("the group {} is not negotiated: {error}", group.name));
        assert_eq!(version.as_deref(), Some("TLSv1.3"));
    }

    let mut untested = Vec::new();
    for scheme in MANDATORY_SIGNATURE_ALGORITHMS {
        if NOT_NEGOTIATED.contains(&scheme.name) {
            untested.push(scheme.name);
            continue;
        }
        let Some(&(_, offered, key)) = SIGALG_ITEMS.iter().find(|item| item.0 == scheme.name)
        else {
            panic!(
                "no test for the mandatory signature algorithm {}",
                scheme.name
            );
        };
        let (_, version) = raw_client(station(key), |builder| {
            with_client_identity(builder);
            builder
                .set_min_proto_version(Some(SslVersion::TLS1_3))
                .expect("TLS 1.3");
            builder.set_sigalgs_list(offered).expect("the scheme");
        })
        .await
        .unwrap_or_else(|error| {
            panic!(
                "the signature algorithm {} is not negotiated: {error}",
                scheme.name
            )
        });
        assert_eq!(version.as_deref(), Some("TLSv1.3"));
    }
    assert_eq!(
        untested,
        ["rsa_pkcs1_sha256"],
        "the untested signature algorithms changed"
    );
}
