// SPDX-FileCopyrightText: 2026 The igs-iec104 contributors
//
// SPDX-License-Identifier: Apache-2.0

//! Emit the generated Rust source of the profile constants. Values are data
//! read from the YAML files; doc comments paraphrase and cite clauses only.

use std::fmt::Write as _;

use crate::data::{Profile, TypeInfo};

const SPDX: &str = "// SPDX-FileCopyrightText: 2026 The igs-iec104 contributors\n\
                    //\n\
                    // SPDX-License-Identifier: Apache-2.0";

/// Turns a data-file reference such as "104 9.5" into "IEC 60870-5-104 9.5".
fn clause(reference: &str) -> String {
    let (standard, rest) = reference.split_once(' ').unwrap_or((reference, ""));
    let standard = match standard {
        "101" => "IEC 60870-5-101",
        "104" => "IEC 60870-5-104",
        other => other,
    };
    if rest.is_empty() {
        standard.to_owned()
    } else {
        format!("{standard} {rest}")
    }
}

/// Bit mask of permitted SQ values: bit 0 for SQ = 0, bit 1 for SQ = 1.
fn sq_mask(values: &[u8]) -> u8 {
    let mut mask = 0u8;
    for value in values {
        mask |= 1 << value;
    }
    mask
}

/// Body of the generated `generated/mod.rs`.
pub fn module_txt() -> String {
    let mut s = String::new();
    s.push_str(SPDX);
    s.push_str("\n\n//! Generated constants of the IEC 60870-5-104 profile.\n//!\n");
    s.push_str("//! Generated by `cargo xtask codegen`, do not edit.\n\n");
    s.push_str("pub mod profile;\n");
    s
}

/// Body of the generated `generated/profile.rs`.
pub fn profile_txt(profile: &Profile) -> String {
    let mut out = String::new();
    out.push_str(SPDX);
    out.push_str("\n\n");
    out.push_str("//! Constants of the IEC 60870-5-104 application profile.\n//!\n");
    out.push_str("//! Generated by `cargo xtask codegen`, do not edit. Run it on a development\n");
    out.push_str("//! machine only: the data files under `docs/spec/` are absent in CI.\n//!\n");
    out.push_str("//! Sources: `docs/spec/104/data/profile_104.yaml` for the ASDU header sizes\n");
    out.push_str("//! (max APDU length: IEC 60870-5-104 9.5), the type catalogue and the\n");
    out.push_str("//! causes of transmission; `docs/spec/5-4/data/formats.yaml` for the size\n");
    out.push_str("//! of the time formats. The cause lists apply the decisions D-001 to D-005\n");
    out.push_str("//! of PROVENANCE.md. Data only: no text of the standards is reproduced.\n");

    write_header(&mut out, profile);
    write_time_tag(&mut out);
    write_enum(&mut out, profile);
    write_cot_arrays(&mut out, profile);
    write_impl(&mut out, profile);
    out
}

fn write_header(out: &mut String, profile: &Profile) {
    let h = &profile.header;
    for (name, value, doc) in [
        (
            "CAUSE_OF_TRANSMISSION_OCTS",
            h.cause_of_transmission_octets,
            "Octets in the cause of transmission field",
        ),
        (
            "COMMON_ADDRESS_OCTS",
            h.common_address_octets,
            "Octets in the common address of ASDU field",
        ),
        (
            "INFO_OBJECT_ADDRESS_OCTS",
            h.information_object_address_octets,
            "Octets in the information object address field",
        ),
    ] {
        let _ = write!(
            out,
            "\n/// {doc}.\n///\n/// {}.\npub const {name}: u8 = {value};\n",
            clause("104 9.5"),
        );
    }
    let _ = write!(
        out,
        "\n/// Largest APDU length, in octets.\n///\n/// {}.\n\
         pub const MAX_APDU_LENGTH: usize = {};\n",
        clause("104 9.5"),
        h.max_apdu_length
    );
}

fn write_time_tag(out: &mut String) {
    let _ = write!(
        out,
        "\n/// The time that every information object of an ASDU type carries.\n\
         #[derive(Copy, Clone, Debug, PartialEq, Eq)]\n\
         pub enum TimeTag {{\n\
         \x20    /// No time tag.\n\
         \x20    None,\n\
         \x20    /// CP24Time2a: three octets, time of day only.\n\
         \x20    Cp24Time2a,\n\
         \x20    /// CP56Time2a: seven octets, full date and time.\n\
         \x20    Cp56Time2a,\n\
         }}\n"
    );
}

fn write_enum(out: &mut String, profile: &Profile) {
    let _ = write!(
        out,
        "\n/// A 104 type identification code.\n///\n\
         /// Holds every type ID known to the catalogue, including the ones the\n\
         /// application profile excludes; `TypeId::in_profile` tells them apart.\n\
         #[repr(u8)]\n\
         #[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]\n\
         #[allow(non_camel_case_types, clippy::upper_case_acronyms)]\n\
         pub enum TypeId {{\n"
    );
    for (id, info) in &profile.type_ids {
        let _ = write!(
            out,
            "\x20    /// {}, {}, defined in {}.\n\x20    {} = {id},\n",
            info.mnemonic,
            info.name,
            clause(&info.defined_in),
            info.mnemonic,
        );
    }
    let _ = writeln!(out, "}}");
}

fn write_cot_arrays(out: &mut String, profile: &Profile) {
    for info in profile.type_ids.values() {
        write_cot(out, "COT_ALLOWED", info, &info.cot_104);
        write_cot(out, "COT_NOT_PERMITTED", info, &info.cot_not_permitted);
    }
}

fn write_cot(out: &mut String, prefix: &str, info: &TypeInfo, values: &[u8]) {
    let label = if prefix == "COT_ALLOWED" {
        "Cause-of-transmission values permitted by the 104 profile"
    } else {
        "Cause-of-transmission values marked not permitted by the profile data"
    };
    let _ = write!(
        out,
        "\n/// {label} for {}.\npub const {prefix}_{}: &[u8] = &[",
        info.mnemonic, info.mnemonic
    );
    for (i, value) in values.iter().enumerate() {
        if i > 0 {
            let _ = write!(out, ",");
        }
        let _ = write!(out, " {value}");
    }
    let _ = writeln!(out, " ];");
}

fn write_impl(out: &mut String, profile: &Profile) {
    let n = profile.type_ids.len();
    let _ = write!(
        out,
        "\nimpl TypeId {{\n\
         \x20    /// How many entries the catalogue holds.\n\
         \x20    pub const COUNT: usize = {n};\n\n\
         \x20    /// Every catalogue entry, in ascending code order.\n\
         \x20    pub const ALL: [TypeId; {n}] = ["
    );
    for info in profile.type_ids.values() {
        let _ = write!(out, " Self::{},", info.mnemonic);
    }
    let _ = write!(
        out,
        " ];\n\n\
         \x20    /// Returns the type identification code octet.\n\
         \x20    pub const fn as_u8(self) -> u8 {{\n\
         \x20        self as u8\n\
         \x20    }}\n\n\
         \x20    /// Turns a type identification code octet into a catalogue entry.\n\
         \x20    pub const fn from_u8(code: u8) -> Option<TypeId> {{\n\
         \x20        match code {{\n"
    );
    for (id, info) in &profile.type_ids {
        let _ = writeln!(
            out,
            "\x20            {id} => Some(Self::{}),",
            info.mnemonic
        );
    }
    let _ = write!(
        out,
        "\x20            _ => None,\n\x20        }}\n\x20    }}\n\n"
    );

    match_fn(
        out,
        "in_profile",
        "Whether this type belongs to the 104 application profile.",
        "bool",
        profile,
        |i| i.in_104_profile.to_string(),
    );
    match_fn(
        out,
        "mnemonic",
        "The ASDU mnemonic of this type, as printed in the catalogue.",
        "&'static str",
        profile,
        |i| format!("{:?}", i.mnemonic),
    );
    match_fn(
        out,
        "sq_allowed_mask",
        "Bit mask of the permitted SQ values: bit 0 for SQ = 0, bit 1 for SQ = 1.",
        "u8",
        profile,
        |i| sq_mask(&i.sq_allowed).to_string(),
    );
    match_fn(
        out,
        "object_size_bits",
        "Size in bits of one information object, or `None` when the length of the\n\
         \x20    /// object depends on its content (file transfer types).",
        "Option<u16>",
        profile,
        |i| match i.object_size_bits {
            Some(bits) => format!("Some({bits})"),
            None => "None".to_owned(),
        },
    );
    match_fn(
        out,
        "time_tag",
        "The time tag carried by each information object of this type.",
        "TimeTag",
        profile,
        |i| match i.time_tag.as_str() {
            "none" => "TimeTag::None".to_owned(),
            "CP24Time2a" => "TimeTag::Cp24Time2a".to_owned(),
            _ => "TimeTag::Cp56Time2a".to_owned(),
        },
    );
    cot_fn(
        out,
        "cot_allowed",
        "Cause-of-transmission values permitted by the profile.",
        "COT_ALLOWED",
        profile,
    );
    cot_fn(
        out,
        "cot_not_permitted",
        "Cause-of-transmission values marked not permitted.",
        "COT_NOT_PERMITTED",
        profile,
    );
    let _ = writeln!(out, "}}");
}

fn match_fn(
    out: &mut String,
    name: &str,
    doc: &str,
    ret: &str,
    profile: &Profile,
    get: fn(&TypeInfo) -> String,
) {
    let _ = write!(
        out,
        "\x20    /// {doc}\n\
         \x20    pub const fn {name}(self) -> {ret} {{\n\
         \x20        match self {{\n"
    );
    for info in profile.type_ids.values() {
        let value = get(info);
        let _ = writeln!(out, "\x20            Self::{} => {value},", info.mnemonic);
    }
    let _ = write!(out, "\x20        }}\n\x20    }}\n\n");
}

fn cot_fn(out: &mut String, name: &str, doc: &str, prefix: &str, profile: &Profile) {
    let _ = write!(
        out,
        "\x20    /// {doc}\n\
         \x20    pub const fn {name}(self) -> &'static [u8] {{\n\
         \x20        match self {{\n"
    );
    for info in profile.type_ids.values() {
        let _ = writeln!(
            out,
            "\x20            Self::{} => {prefix}_{},",
            info.mnemonic, info.mnemonic
        );
    }
    let _ = write!(out, "\x20        }}\n\x20    }}\n");
}
